_target_: src.models.pygo_yolo_module.PyGoYoloModule
optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.0001
  weight_decay: 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max : 3

net:
  _target_: src.models.pygo_yolo_module.PyGoYoloModule

# compile model for faster training with pytorch 2.0
compile: false
